/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author unifpmotta
 */
public class JanelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form JanelaInicial
     */    
    public JanelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAlimento = new javax.swing.JButton();
        btBebida = new javax.swing.JButton();
        btPesquisa = new javax.swing.JButton();
        btCarrinho = new javax.swing.JButton();
        btHistorico = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btEstabelicimento = new javax.swing.JButton();
        btAvaliacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAlimento.setText("Alimento");
        btAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlimentoActionPerformed(evt);
            }
        });

        btBebida.setText("Bebida");
        btBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBebidaActionPerformed(evt);
            }
        });

        btPesquisa.setText("Pesquisa");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        btCarrinho.setText("Carrinho");
        btCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarrinhoActionPerformed(evt);
            }
        });

        btHistorico.setText("Histórico");
        btHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoricoActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btEstabelicimento.setText("Estabelicimento");
        btEstabelicimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstabelicimentoActionPerformed(evt);
            }
        });

        btAvaliacao.setText("Avaliação");
        btAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvaliacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAlimento)
                .addGap(18, 18, 18)
                .addComponent(btBebida)
                .addGap(18, 18, 18)
                .addComponent(btPesquisa)
                .addGap(18, 18, 18)
                .addComponent(btCarrinho)
                .addGap(18, 18, 18)
                .addComponent(btEstabelicimento)
                .addGap(18, 18, 18)
                .addComponent(btHistorico)
                .addGap(18, 18, 18)
                .addComponent(btAvaliacao)
                .addGap(18, 18, 18)
                .addComponent(btVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlimento)
                    .addComponent(btBebida)
                    .addComponent(btPesquisa)
                    .addComponent(btCarrinho)
                    .addComponent(btVoltar)
                    .addComponent(btEstabelicimento)
                    .addComponent(btHistorico)
                    .addComponent(btAvaliacao))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoricoActionPerformed
        this.dispose();
        Historico janelaHistorico = new Historico();
        janelaHistorico.setVisible(true);
    }//GEN-LAST:event_btHistoricoActionPerformed

    private void btAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlimentoActionPerformed
        this.dispose();
        Alimento janelaComida = new Alimento();
        janelaComida.setVisible(true);
    }//GEN-LAST:event_btAlimentoActionPerformed

    private void btBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBebidaActionPerformed
        this.dispose();
        Bebida janelaAvaliacao = new Bebida();
        janelaAvaliacao.setVisible(true);
    }//GEN-LAST:event_btBebidaActionPerformed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        this.dispose();
        Pesquisa janelaPesquisa = new Pesquisa();
        janelaPesquisa.setVisible(true);
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void btCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarrinhoActionPerformed
        this.dispose();
        Carrinho janelaCarrinho = new Carrinho();
        janelaCarrinho.setVisible(true);
    }//GEN-LAST:event_btCarrinhoActionPerformed

    private void btEstabelicimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstabelicimentoActionPerformed
        this.dispose();
        Estabelicimento janelaEstabelicimento = new Estabelicimento();
        janelaEstabelicimento.setVisible(true);
    }//GEN-LAST:event_btEstabelicimentoActionPerformed

    private void btAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvaliacaoActionPerformed
        this.dispose();
        Avaliacao janelaBebida = new Avaliacao();
        janelaBebida.setVisible(true);
    }//GEN-LAST:event_btAvaliacaoActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
        Cadastro janelaCadastro = new Cadastro();
        janelaCadastro.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlimento;
    private javax.swing.JButton btAvaliacao;
    private javax.swing.JButton btBebida;
    private javax.swing.JButton btCarrinho;
    private javax.swing.JButton btEstabelicimento;
    private javax.swing.JButton btHistorico;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btVoltar;
    // End of variables declaration//GEN-END:variables
}
