package view;

import controller.ControleHistorico;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

public class Historico extends javax.swing.JFrame {

    private ControleHistorico controle;

    public Historico() {
        initComponents();
        controle = new ControleHistorico(this); // conecta o controller
    }

    // Getters para o controller acessar os componentes
    public JTextField getTxtPesquisaParaSalvarEmail() {
        return txtPesquisaParaSalvarEmail;
    }

    public JTextArea getTxtResultadoSalvoNaLista() {
        return txtResultadoSalvoNaLista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVoltar2 = new javax.swing.JButton();
        txtPesquisaParaSalvarEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btListaDoAlimentoSalvo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultadoSalvoNaLista = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btVoltar2.setText("Voltar");
        btVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar2ActionPerformed(evt);
            }
        });

        txtPesquisaParaSalvarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaParaSalvarEmailActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Email:");

        btListaDoAlimentoSalvo.setText("Listar");
        btListaDoAlimentoSalvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaDoAlimentoSalvoActionPerformed(evt);
            }
        });

        txtResultadoSalvoNaLista.setColumns(20);
        txtResultadoSalvoNaLista.setRows(5);
        txtResultadoSalvoNaLista.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtResultadoSalvoNaListaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(txtResultadoSalvoNaLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btVoltar2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btListaDoAlimentoSalvo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPesquisaParaSalvarEmail))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltar2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaParaSalvarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btListaDoAlimentoSalvo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar2ActionPerformed
        this.dispose();
        JanelaInicial janelaInicial = new JanelaInicial();
        janelaInicial.setVisible(true);
    }//GEN-LAST:event_btVoltar2ActionPerformed

    private void txtPesquisaParaSalvarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaParaSalvarEmailActionPerformed

    }//GEN-LAST:event_txtPesquisaParaSalvarEmailActionPerformed

    private void txtResultadoSalvoNaListaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtResultadoSalvoNaListaAncestorAdded

    }//GEN-LAST:event_txtResultadoSalvoNaListaAncestorAdded

    private void btListaDoAlimentoSalvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaDoAlimentoSalvoActionPerformed
        String email = txtPesquisaParaSalvarEmail.getText().trim();

            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Digite um email para buscar o histórico.");
                return;
            }

            controle.buscarHistorico(email);
    }//GEN-LAST:event_btListaDoAlimentoSalvoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListaDoAlimentoSalvo;
    private javax.swing.JButton btVoltar2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPesquisaParaSalvarEmail;
    private javax.swing.JTextArea txtResultadoSalvoNaLista;
    // End of variables declaration//GEN-END:variables
}
